version: "3.9"
services:
  discovery:
    image: consul:1.15
    ports:
      - 8500:8500

  serveur-conf:
    image: ghcr.io/laurich-app/serveur-conf:0.0.3
    ports:
      - 8888:8888
    environment:
      - CONSUL_HOST=discovery

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  postgres:
    image: postgres:12.17
    environment:
      - POSTGRES_DB=service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  service-utilisateur:
    image: ghcr.io/laurich-app/service-utilisateur:1.1.0
    ports:
      - 8081:8080
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - PRIVATE_KEY=app_pkcs8.prv
      - PUBLIC_KEY=app.pub
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PSWD=pswd
    depends_on:
      - serveur-conf
      - discovery


  postgres-catalogue:
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=service-catalogue
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  rabbit:
    image: rabbitmq:3.12.13-management
    ports:
      - 15672:15672
      - 5672:5672

  mongo-commande:
    image: mongo:7.0.5
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pswd

  mongo-express:
    image: mongo-express:1.0.2-20
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pswd
      ME_CONFIG_MONGODB_URL: mongodb://user:pswd@mongo-commande:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo-commande
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true