POST http://localhost:8081/auth/connexion
Content-Type: application/json

{
  "email": "root@root.com",
  "motDePasse": "root"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    if(response.status === 200) {
        client.global.set("accessToken", response.headers.valueOf("Authorization").slice(7));
    }
%}

####

GET http://localhost:8080/produits
Content-Type: application/json
Authorization: Bearer {{accessToken}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
